name: Clang-Tidy Code Scanning

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  merge_group:
    types: [checks_requested]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  clang-tidy:
    name: Run Clang-Tidy

    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: "true"

      - name: Setup sccache
        uses: hendrikmuhs/ccache-action@v1.2.20
        with:
          variant: sccache

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Run build
        # TODO(@getchoo): Figure out how to make this work with PCH
        run: |
          nix develop --command bash -c '
            cmake -B build -D Launcher_USE_PCH=OFF -D CMAKE_CXX_COMPILER_LAUNCHER=sccache && cmake --build build
          '

      - name: Run clang-tidy
        run: |
          nix develop --command bash -c '
            run-clang-tidy -- | clang-tidy-sarif | tee results.sarif | sarif-fmt
          '

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
